spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stayndine_customers?sslMode=DISABLED&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: stayndine_customers_app
    password: Mariano!1941
  jpa:
    show-sql: true
  threads:
    virtual:
      enabled: true

internal:
  api-key: "internal-key"

logging:
  level:
    root: INFO
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
