spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stayndine_customers?sslMode=DISABLED&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: stayndine_customers_app
    password: Mariano!1941
  jpa:
    show-sql: true
  threads:
    virtual:
      enabled: true

internal:
  api-key: "internal-key"

logging:
  level:
    root: INFO
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

cors:
  allowed-origins:
    - "http://localhost:5173"
    - "http://127.0.0.1:5173"
  allowed-methods: [ GET, POST, PUT, PATCH, DELETE, OPTIONS ]
  allowed-headers: [ Authorization, Content-Type, X-Requested-With ]
  exposed-headers: [ Location ]
  allow-credentials: false
