spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stayndine_customers?sslMode=DISABLED&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: stayndine_customers_app
    password: Mariano!1941
  jpa:
    show-sql: true
  threads:
    virtual:
      enabled: true

security:
  jwt:
    issuer: "stayndine-identity"
    secret: "a1d8b7e0d2b34d3c8f6a9e0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0"
  internal:
    api-key-in: "internal-key"

clients:
  identity:
    base-url: "http://localhost:8000"
    internal-api-key: "internal-key"

logging:
  level:
    root: INFO
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
